/**
 * Generated by FITpro Fixture Generator
 */
package Fixtures;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Date;

import client.ClientConsole;
import client.DefineCourseGUIController;
import client.MsgFromServer;
import client.newAssTeacher;
import entity.Assigenment;
import entity.Course;
import entity.User;
import fit.ActionFixture;
import jdk.nashorn.internal.ir.Assignment;
import thred.IndexList;

/*
 * TODO: modify class to match the FIT test - edit and add methods as required.
 */
public class TestCreateNewAss extends ActionFixture {

	public ClientConsole cli = new ClientConsole("127.0.0.1", 5555);
    private String cid, name, description, date;
    private int flag = 0;
    
	public String assignmentUploaded() {
		if (flag == 0) return "false";
		else return "true";
	}
  
    
	public String courseExists() {
		Course c = new Course();
		c.setCourseId(cid);
		return DefineCourseGUIController.courseExists(c);
	}
  
    
	public void insertCourseid(String insertCourseid) {
		cid = insertCourseid;
	}
  
    
	public void insertDescription(String insertDescription) {
		description = insertDescription;
	}
  
    
	public void insertDueDate(String insertDueDate) {
		date = insertDueDate;
	}
  
    
	public void insertName(String insertName) {
		name = insertName;
	}
  
    
	public String returnDescription() {
		return description;
	}
  
    
	public String returnDueDate() {
		return date;
	}
  
    
	public String returnName() {
		return name;
	}
  
	public void uploadAssignment(String uploadAssignment) {
		File f = new File("C:\\MAT-LocalFiles\\nullFile.txt");
		Assigenment ass = new Assigenment();
		ass.setAssname(name);
		ass.setUserId("634667188");
		ass.setCourseid("01100");
		ass.setPath(f.getAbsolutePath());
		ass.setFileid(f.getName());
		Path path = Paths.get(ass.getPath());
		try {
			ass.setData(Files.readAllBytes(path));
		} catch (IOException e) {
			
			e.printStackTrace();
		}
		ass.setDueDate(new Date());
		if (newAssTeacher.newAss(ass) == 1) flag = 1;
	}
}

