/**
 * Generated by FITpro Fixture Generator
 */
package Fixtures;

import client.ClientConsole;
import client.RemoveCourseGUIController;
import client.DefineCourseGUIController;
import fit.ActionFixture;
import entity.Course;

/*
 * TODO: modify class to match the FIT test - edit and add methods as required.
 */
public class TestDefNewCourse extends ActionFixture {

	public ClientConsole cli = new ClientConsole("127.0.0.1", 5555);

	private Course c;

	private String name;

	private String cid;

	private String uid;

	private int hours;

	public String courseExists() {

		c = new Course();
		c.setName(name);
		c.setCourseId(cid);
		c.setUnit(uid);
		c.setHours(hours);
		return DefineCourseGUIController.courseExists(c);
	}

	public void defineCourse(String defineCourse) {

		c = new Course();
		c.setName(name);
		c.setCourseId(cid);
		c.setUnit(uid);
		c.setHours(hours);
		DefineCourseGUIController.defNewCourse(c);
	}

	public void insertCourseID(String insertCourseID) {

		cid = insertCourseID;
	}

	public void insertName(String insertName) {

		name = insertName;
	}

	public void insertUnitID(String insertUnitID) {

		uid = insertUnitID;
	}

	public void insertWeeklyHours(String insertWeeklyHours) {

		hours = Integer.parseInt(insertWeeklyHours);
	}

	public void removeCourse(String removeCourse) {

		c = new Course();
		c.setName(name);
		c.setCourseId(cid);
		c.setUnit(uid);
		c.setHours(hours);
		RemoveCourseGUIController.removeCourse(c);
	}

	public String retCourseID() {

		return cid;
	}

	public String retName() {

		return name;
	}

	public String retUnitID() {

		return uid;
	}

	public String retWeeklyHours() {

		return "" + hours;
	}

}
